config/routes.rb
Rails.application.routes.draw do
  
  resources :skills, only: [:new, :create, :destroy]

  resources :locations, only: [:new, :create, :destroy]

  root 'users#welcome'

  resources :messages, only: [:new, :create, :destroy]
  
  resource :session, only: [:new, :create, :destroy]

  resources :industries, only: [:new, :create, :destroy]

  resources :availabilities, only: [:new, :create, :destroy]

  get 'users/mentees', to: "users#mentees"
  get 'users/mentors', to: "users#mentors"

  resources :users do
    resources :filters, only: [:new, :create, :index, :show, :update]

  end

  resources :auth, only: :index

  get '/auth/callback' => "auth#show"

  get '/auth/profile', to: "auth#profile"

  get '/about', to: "users#about"

  get '/testimonials', to: "users#testimonials"

  get '/contact', to: "users#contact"

  get '/forgot', to: "users#forgot"

  get 'users/:id/ziggeo', to: "users#ziggeo"

  

end

app/models/auth.rb
# class Auth < ActiveRecord::Base
# 	attr_reader :oauth
# 	def auth_method
# 		@oauth = LinkedIn::OAuth2.new
# 		@oauth
# 	end

# end

app/models/availability.rb
class Availability < ActiveRecord::Base
  has_many :users
end

app/models/filter.rb
class Filter <  ActiveRecord::Base

end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_many :users
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :users
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many :users_skills
	has_many :users, :through => :users_skills
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :filter_results
 has_secure_password

 validates :name, :email, presence: true

 belongs_to :location
 belongs_to :industry
 belongs_to :availability

 has_many :users_skills, class_name: UsersSkill
 has_many :skills, :through => :users_skills

 belongs_to :role


end

app/models/users_skill.rb
class UsersSkill < ActiveRecord::Base

	belongs_to :skill
	belongs_to :user
	
end

app/models/userskill.rb
class Userskill < ActiveRecord::Base

	belongs_to :skill
	belongs_to :user
	
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/filters_helper.rb
module FiltersHelper


end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MentorMatch</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<% if current_user %>
  <%=link_to image_tag("MentorMatch_Logo.png", alt: "MentorMatch", class: "logo clearfix" ), "/users/mentors" %>
  <ul class="company-name">
    <li><%= link_to("mentor match", "/users/mentors") %></li>
  </ul>
<% else %> 
  <%=link_to image_tag("MentorMatch_Logo.png", alt: "MentorMatch", class: "logo clearfix" ), root_path %>
  <ul class="company-name">
    <li><%= link_to("mentor match", root_path) %></li>
  </ul>
<% end %>


<nav>
  <ul class="logged-out">
    <li><%= link_to "about", "/about" %></li>
    <li><%= link_to "testimonials", "/testimonials" %></li>
    <li><%= link_to "contact", "/contact" %></li>
  </ul>

  <% if current_user == nil %>
    <ul class="signup"> 
      <li> <%= link_to "sign up", new_user_url %></li>
      <li> | </li>
      <li> <%= link_to "log in", new_session_url %></li>
    </ul>
  <% else %>
    <ul class="signup"> 
      <li> <%= link_to "sign out", session_url, method: "delete" %></li>
    </ul>
  <% end %>
</nav>

<hr>

<% if current_user %>
  <nav class="logged-in clearfix">
    <ul>
      <li>
        <%= link_to "mentors", "/users/mentors" %>
      </li>
      <li>
        <%= link_to "mentees", "/users/mentees" %>
      </li>
      <li>
        <%= link_to "profile", user_url(current_user) %>
      </li>
<!--       <li>
        <%= link_to "Filter Search",  '/users/:user_id/filters/new' %>
      </li> -->
    </ul>
  </nav>
<% end %>
  

<%= yield %>

<!-- <pre> session.to_hash.to_yaml </pre> -->
 
</body>
</html>